# Generated by Django 2.1 on 2018-10-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='feedback',
            field=models.TextField(default='This project is still in progress.'),
            preserve_default=False,
        ),
    ]
