# Generated by Django 2.1 on 2018-10-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='headertext',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
