# Generated by Django 2.1 on 2018-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link_url',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
    ]
