# Generated by Django 2.1 on 2018-10-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('company', models.CharField(max_length=200)),
                ('reference_name', models.TextField()),
                ('email_address', models.TextField()),
            ],
        ),
    ]
