# Generated by Django 2.1 on 2018-10-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_header',
            field=models.TextField(default='Text here'),
            preserve_default=False,
        ),
    ]
